DEBUG = TRUE

!IF "$(DEBUG)" == "TRUE"
COPT = /c /W3 /AL /Od /Zip /nologo
LOPT = /CO/NOLOGO/NOE/St:18000
LIBS = GnuLibDR
EXCP = rem
!ELSE
COPT = /c /W3 /AL /Ox /Grs /Zp /nologo
LOPT = /E/F/PACKC/NOLOGO/NOE/St:18000
LIBS = GnuLibOR
EXCP = pklite -p
!ENDIF

PROG = cvtbtab

all : $(PROG).exe

$(PROG).obj : $(PROG).c
  cl $(COPT) $*.c

xls.obj : xls.c
  cl $(COPT) $*.c

wk1.obj : wk1.c
  cl $(COPT) $*.c

dif.obj : dif.c
  cl $(COPT) $*.c

$(PROG).exe : $(PROG).obj xls.obj wk1.obj dif.obj
  link $*  xls wk1 dif $(LOPT),,NUL,$(LIBS);
  $(EXCP) $(@B).EXE
